---
#
# Ansible managed
#
repository:
  description: Install and configure certbot on your system.
  homepage: https://buluma.github.io/
  topics: certbot, acme, letsencrypt, ansible, molecule, tox, playbook, hacktoberfest
