---
- name: converge
  hosts: all
  become: true
  gather_facts: true

  roles:
    - role: ansible-role-certbot
      certbot_email: mail@email.com
      certbot_domains:
        - buluma.me.ke
        - buluma.co.ke
      certbot_ci_mode: true
