---
- name: converge
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: ansible-role-certbot
      certbot_email: mail@email.com
      certbot_domains:
        - buluma.me.ke
        - buluma.co.ke
      certbot_ci_mode: yes
